package com.nhduong.monkeyblog.model;
// Generated May 23, 2017 10:37:10 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images", catalog = "monkeyblog")
public class Images implements java.io.Serializable {

	private int id;

	public Images() {
	}

	public Images(int id) {
		this.id = id;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
